### ISSUE TITLE
Fase 3 — Move the release readers to `scjn.release`, disk-first, with their own cache directory

### ISSUE THREAD

**Issue by mgraffg** [INGEOTEC/LegalIA#209]
Fase 3 of #206. Depends on #208, and on **#205 landing first** — #205 decides
the precedents this phase generalizes (cache-first slug discovery,
`slugs=None` meaning "every law this machine has", and whether a reader may
degrade when an asset is missing). Do not re-litigate those three here; apply
them to the other readers.

Two things happen together because they cannot be separated: the release
readers move to the `scjn` package, and they stop downloading. Moving them
while keeping the three-mode `cache_dir`/`refrescar`/`timeout` signature would
carry the mixture across the new boundary and make it the new package's public
API.

## The move

`packages/nota2md/nota2md/scjn.py` 1205-1827 -> `packages/scjn/scjn/release.py`,
plus a new `packages/scjn/scjn/cache.py` holding the asset half of
`nota2md/cache.py` (`SUFIJO_PARCIAL`, `descarga`, `asset_en_cache`,
`bytes_de_asset`, `resuelve_cache_dir`, and the package's own `CACHE_DIR`).

- To `scjn.release`: `_SCJN_LEYES_RELEASE`, `_SCJN_LEYES_RELEASES_API`,
  `ASSET_INDICE_GLOBAL`, `construye_indice_global`, `_assets_scjn_leyes`,
  `_url_de_asset`, `_bytes_de_asset`, `download_scjn_leyes_index`,
  `markdown_de_snapshot`, `download_scjn_leyes_corpus`,
  `iter_current_federal_laws`, `_estado_de_asset`,
  `download_scjn_leyes_catalog`, `scjn_leyes_slugs`,
  `download_scjn_leyes_assets`, and #205's `_slugs_en_cache`.
- To `nota2md.linking` (from Fase 2): `localiza_codNota` and
  `snapshot_de_codNota` — keyed by a DOF concept, so they stay in `nota2md`
  and now call `scjn.release`'s readers.
- Then **delete `packages/nota2md/nota2md/scjn.py` and
  `packages/nota2md/nota2md/scjn_api.py`.** Nothing re-exports from them any
  more.

`nota2md/cache.py` keeps the DOF side untouched: `directorio_de_salida`,
`escribe_texto`, `SUBDIR_DOF`, and `SUBDIR_MD_SCJN` — which is *not* an
asset path but where `builder.py:395` writes the Markdown it derives from a
snapshot. Those outputs stay in `nota2md`'s cache; only the release assets
move.

## The disk-first contract

`nota2md download all` (and the new `scjn download`) puts everything on disk;
every reader then assumes disk.

1. **Readers read.** `download_scjn_leyes_index`, `download_scjn_leyes_corpus`,
   `download_scjn_leyes_catalog`, `markdown_de_snapshot`,
   `iter_current_federal_laws` take `cache_dir` defaulting to
   `scjn.cache.CACHE_DIR` and open files. No `requests` call on any of their
   paths — assert it in a test with a fake that raises on any HTTP call.
   Downloading stays in `download_scjn_leyes_assets` and the CLI, which keep
   `refrescar` and `timeout`; the readers lose both.
2. **A missing asset raises something a caller can act on.** One exception,
   `scjn.AssetNotCached`, whose message names the asset and the command that
   fetches it (`scjn download --slug lfca`, or `nota2md download all`).
   Today's failure is a `KeyError` out of `_url_de_asset` *after* an HTTP
   attempt (`download_scjn_leyes_catalog`'s docstring even documents the
   `KeyError`); that goes.
3. **`cache_dir=None` — read into memory, cache nothing — is removed**, with
   `SIN_CACHE_DIR` along with it on the `scjn` side (`nota2md.cache` keeps its
   own sentinel for the DOF paths). It exists for doctest/CI paths; those get
   a `tmp_path` plus an explicit `download_scjn_leyes_assets(cache_dir=...)`
   instead. Grep the tests and the docs for `SIN_CACHE_DIR` before removing —
   `tests/test_cache.py`, `test_scjn_release_red.py` and the scripts all use
   it.
4. **"Which laws are there" is answered off disk, everywhere.** #205's
   `_slugs_en_cache` becomes the public `scjn.local_slugs(cache_dir=...)` and
   is what every reader uses when no explicit `slugs` are given.
   `scjn_leyes_slugs(timeout)` survives as the *downloader's* question ("what
   does the release publish"), not the reader's. Carry over #205's reason for
   listing assets rather than `indice-global.json.gz`'s `instrumentos`: a law
   crawled but not linked has a `.tgz` and no index entry.
5. **`download_scjn_leyes_catalog` stops being a 380 MB default.**
   `freshness=True` reads `estado.json` out of the tarballs already on disk
   and reports nothing for the laws whose tarball is absent (following
   whatever #205 decided about degrading vs raising, and saying which laws
   were skipped). It never fetches 316 tarballs to read four fields.

## The cache directory (#206 §1(c))

`scjn` gets its own `CACHE_DIR` — `platformdirs` under the name `scjn`,
overridable with `$SCJN_CACHE_DIR` — because the project's own rule already
says two releases with two lifecycles do not share a directory, and because a
package that must not import `nota2md` cannot name `nota2md`'s directory.

The orphan is real (~380 MB in every existing cache), so migrate once, and
narrowly:

- On first resolve, if `$SCJN_CACHE_DIR`/`CACHE_DIR` does not exist and the
  legacy `<platformdirs nota2md cache>/scjn-leyes/` does, move **only the
  release assets** (`*.tgz`, `*.tgz.parcial`, `indice-global.json.gz`,
  `SHA256SUMS.txt`) with `os.replace`, and leave `md/` where it is — that
  subdirectory is `nota2md`'s output, not an asset (`cache.SUBDIR_MD_SCJN`),
  and moving it would break `legal_provisions`' documented return path.
- Compute the legacy path with `platformdirs` directly (three lines), never by
  importing `nota2md`.
- If the move fails (different filesystem, permissions), do not copy 380 MB
  silently: leave the files, warn once naming both paths, and read the legacy
  directory for that process.
- Print what happened on the first migrating run, and mention it in the
  package README. A silent 380 MB move is the kind of surprise this project
  writes comments about.

## CLI (#206 §1(d))

`scjn` gets its own console script: `scjn download [--slug SLUG] [--cache-dir]
[--refrescar]`, the verb that puts the release on disk. `nota2md download
federal-laws` and `nota2md download all` **keep working by delegating to it** —
`nota2md` depends on `scjn`, so it is always installed, and both verbs are
already documented in `packages/nota2md/README.md` and on Read the Docs.
Delegation, not a second implementation: `nota2md.cli._descarga_federal_laws`
calls `scjn`'s downloader and prints the same summary line.

## Public API (#206 §1(f))

`download_scjn_leyes_corpus`, `download_scjn_leyes_index`,
`download_scjn_leyes_catalog` and `iter_current_federal_laws` are in
`nota2md.__all__` and on Read the Docs. Their canonical home becomes
`scjn.__all__`; **`nota2md` re-exports all four**, keeps them in its own
`__all__`, and `from nota2md import download_scjn_leyes_corpus` keeps working
unchanged. No deprecation, no removal — the import path costs one line and
breaking it would buy nothing. `markdown_de_snapshot` (not in `__all__`) moves
outright.

`scjn.__all__` after this phase: the four above, plus `markdown_de_snapshot`,
`download_scjn_leyes_assets`, `local_slugs` and `AssetNotCached`. The SCOW
transport (`scjn.api`) stays public but out of `__all__` — see Fase 6 for how
it is documented.

## What must not change

The release format. `indice.json`, `estado.json` and
`indice-global.json.gz` keep their names, their shapes and their fields,
including the six `nota2md`-owned link fields, which `construye_indice_global`
carries through opaquely (#206 §1(e)). An existing tarball must still read
correctly after this phase — that is the whole reason the format work is
Fase 4 and not here.

## Definition of done

- `nota2md/scjn.py` and `nota2md/scjn_api.py` no longer exist.
- A test proves every reader is offline: monkeypatch `requests.get` to raise,
  point `cache_dir` at a populated fixture directory, call all five.
- `nota2md download federal-laws --slug lfca` and `scjn download --slug lfca`
  produce the same directory contents.
- A cache populated before this change is picked up automatically, with
  `md/` still under `nota2md`'s cache and the tarballs under `scjn`'s.
- `pytest packages/scjn -q`, `pytest packages/nota2md -q` (network files
  ignored), and the two red files run by hand.

## Machine notes

This phase needs the corpus. On the dedicated machine, before starting:
`nota2md download all` (~380 MB for `scjn-leyes` plus the `notas-archivo`
cache), and keep a *second* copy of `~/.cache/nota2md/scjn-leyes/` — the
migration path is easier to test against a cache you can restore.

**Comment by mgraffg** [comment]
Implemented on `branch-205-206-212`, commit `723fb6d15e264128ec0fa730c0ab729d40159c64`.

**What moved:**
- New `scjn.release`: every scjn-leyes release reader
  (`download_scjn_leyes_index/_corpus/_catalog`, `markdown_de_snapshot`,
  `iter_current_federal_laws`, `local_slugs`), now **disk-first** — none of
  them touch the network, and a missing asset raises the new
  `scjn.release.AssetNotCached` instead of a `KeyError` reached after an HTTP
  attempt. `readers lose `refrescar`/`timeout`; `download_scjn_leyes_assets`
  (and the new `scjn download` CLI) is the only thing that still downloads.
- New `scjn.cache`: the asset half of `nota2md/cache.py`, plus
  `migrate_legacy_assets` — a **pure, generic** move (both directories
  explicit parameters, zero knowledge of "nota2md") since `scjn` must never
  import or even name a downstream package (enforced by its own
  `test_boundary.py`, which I had to rewrite several docstrings around —
  literally every mention of "nota2md"/"dofjson" anywhere in
  `packages/scjn/scjn/*.py`, including comments, fails that test).
- `localiza_codNota`/`snapshot_de_codNota` move to `nota2md.linking` (not
  `scjn.release`) — DOF-keyed, so they stay in `nota2md`, now calling
  `scjn.release`'s disk-first readers.
- `nota2md/scjn.py` and `nota2md/scjn_api.py` are **deleted**. `nota2md`'s
  public `download_scjn_leyes_corpus/_index/_catalog`/`iter_current_federal_laws`
  keep working unchanged, re-exported straight from `scjn` (which now has a
  public `scjn.__all__` of 8 names).
- `scjn` gets its own console script: `scjn download [--slug] [--cache-dir] [--refrescar]`.
  `nota2md download federal-laws`/`all` delegate to it.

**The cache split & migration:** `scjn` now caches under `scjn.cache.CACHE_DIR`
(`$SCJN_CACHE_DIR`, default `~/.cache/scjn`) — a separate directory/lifecycle
from `nota2md`'s. Since `scjn` can't know `nota2md`'s legacy cache location,
`nota2md.cli._descarga_federal_laws` is the one place that hands that
knowledge off: on `download federal-laws`/`all` with no explicit
`--cache-dir`, it calls `scjn.cache.migrate_legacy_assets` once, moving
`*.tgz`/`indice-global.json.gz`/`SHA256SUMS.txt` out of the legacy
`<nota2md cache>/scjn-leyes/` and leaving `md/` (nota2md's own derived output)
untouched.

**Verified against this machine's real ~380 MB legacy cache** (with the
user's explicit go-ahead per the run's DEFAULT 3, since this is exactly the
one-time migration the feature exists for): `nota2md download federal-laws
--slug lfca` printed `scjn-leyes: migrated 316 asset(s) from the pre-#209
nota2md cache (...) into .../scjn-leyes`, left `~/.cache/nota2md/scjn-leyes/`
holding only `md/` afterward, a second run was idempotent (no re-migration,
\"already cached\"), and `nota2md 5788357` correctly built `lfca-22-05-2026.md`
from the migrated tarball. Also confirmed `nota2md download federal-laws
--slug lfca` and `scjn download --slug lfca` write byte-identical directory
layouts into a fresh `--cache-dir` (Definition of Done's explicit check).

**Bug found via that manual check, fixed:** `scjn.cli.main()` was returning
`_main_download`'s result list; since the console-script wrapper does
`sys.exit(main())`, a truthy non-int return value made every real `scjn
download` invocation exit 1 despite succeeding. Fixed to match `nota2md.cli.main`'s
own pattern (no return of a subcommand's result).

**Judgment calls:**
1. `AssetNotCached`'s message and every scjn-side docstring avoid naming
   `nota2md`/its CLI verbs at all (not even \"or `nota2md download
   federal-laws`\") — the boundary test's grep is literal and repo-wide over
   `packages/scjn/scjn/*.py`, so anything short of that fails it.
2. `iter_current_federal_laws`'s cold-cache fallback to `scjn_leyes_slugs()`
   (added in #205) is **removed**: the issue's own "no requests call on any
   of `iter_current_federal_laws`'s paths" is a stronger, later instruction
   than #205's fallback, so a cold/absent cache now yields nothing rather
   than reaching the network. `scjn_leyes_slugs` itself is untouched and
   still used by the downloader.
3. `test_scjn_release_red.py` split rather than moved wholesale: its
   `scjn.release`-only assertions (index shape, disk cache, resolving a
   codNota's snapshot) moved to `packages/scjn/tests/test_release_red.py`;
   its `legal_provisions`-level assertions were judged already covered by
   the mocked `test_builder_scjn.py` and dropped rather than duplicated as a
   second network-dependent file.
4. Fixed `scripts/fetch_lfiiedb_dof.py`'s missing `packages/scjn` sys.path
   entry (an #207 gap, not introduced here) — without it the script's
   `--help` raised `ImportError: cannot import name 'download_scjn_leyes_catalog'
   from 'scjn' (unknown location)\", because `scripts/scjn/` (a gitignored
   scratch directory) shadows the real package as a namespace package once
   `scripts/` is on `sys.path` first.
5. Left `docs/source/nota2md_api.rst`'s `.. automodule:: nota2md.scjn`/
   `nota2md.scjn_api` directives as-is (already broken since #207 deleted
   `scjn_api.py` without updating docs) — the full Read the Docs rewrite for
   this architecture is explicitly Fase 6/#212's own deliverable
   (`docs/source/scjn_api.rst`), and a partial fix here would just be redone.

**Tests:** `pytest packages/nota2md -q`: 168 passed, 46 subtests passed.
`pytest packages/scjn -q` (includes `test_api_red.py` and the new
`test_release_red.py`, both run for real against the network per this run's
own rule): 166 passed. All nine scjn-adjacent scripts verified with
`--help`.
